/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.elisa.rest.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.elisa.rest.app.AppKt")
}
