/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.elisa.rest.app

import io.github.elisa.rest.core.MainCore
import io.github.elisa.rest.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
    MainCore().coreMethod();
}
